<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Mentor;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MentorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing mentors
        DB::table('mentors')->delete();

        $mentors = [
            [
                'name' => 'Dr. Sarah Johnson',
                'email' => 'sarah.johnson@example.com',
                'phone' => '+62 812-3456-7890',
                'bio' => 'Expert in modern web development technologies with extensive experience in React, Vue, and Laravel.',
                'specialization' => 'Web Development',
                'experience' => '5+ years',
                'rating' => 4.8,
                'students_taught' => 250,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Sarah+Johnson&color=7F9CF5&background=EBF4FF',
                'slug' => 'sarah-johnson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Prof. Michael Chen',
                'email' => 'michael.chen@example.com',
                'phone' => '+62 813-4567-8901',
                'bio' => 'Data science expert specializing in machine learning, deep learning, and statistical analysis.',
                'specialization' => 'Data Science',
                'experience' => '10+ years',
                'rating' => 4.9,
                'students_taught' => 500,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Michael+Chen&color=7F9CF5&background=EBF4FF',
                'slug' => 'michael-chen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Emily Rodriguez',
                'email' => 'emily.rodriguez@example.com',
                'phone' => '+62 814-5678-9012',
                'bio' => 'Mobile development specialist with expertise in iOS and Android native development.',
                'specialization' => 'Mobile Development',
                'experience' => '7+ years',
                'rating' => 4.7,
                'students_taught' => 300,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Emily+Rodriguez&color=7F9CF5&background=EBF4FF',
                'slug' => 'emily-rodriguez',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'James Wilson',
                'email' => 'james.wilson@example.com',
                'phone' => '+62 815-6789-0123',
                'bio' => 'Creative UI/UX designer with a passion for user-centered design and accessibility.',
                'specialization' => 'UI/UX Design',
                'experience' => '6+ years',
                'rating' => 4.6,
                'students_taught' => 200,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=James+Wilson&color=7F9CF5&background=EBF4FF',
                'slug' => 'james-wilson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Lisa Anderson',
                'email' => 'lisa.anderson@example.com',
                'phone' => '+62 816-7890-1234',
                'bio' => 'Cloud computing architect with expertise in AWS, Azure, and Google Cloud Platform.',
                'specialization' => 'Cloud Computing',
                'experience' => '8+ years',
                'rating' => 4.8,
                'students_taught' => 350,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Lisa+Anderson&color=7F9CF5&background=EBF4FF',
                'slug' => 'lisa-anderson',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Robert Taylor',
                'email' => 'robert.taylor@example.com',
                'phone' => '+62 817-8901-2345',
                'bio' => 'DevOps engineer specializing in CI/CD pipelines, containerization, and infrastructure as code.',
                'specialization' => 'DevOps',
                'experience' => '9+ years',
                'rating' => 4.7,
                'students_taught' => 400,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Robert+Taylor&color=7F9CF5&background=EBF4FF',
                'slug' => 'robert-taylor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Maria Garcia',
                'email' => 'maria.garcia@example.com',
                'phone' => '+62 818-9012-3456',
                'bio' => 'Machine learning researcher with expertise in neural networks and natural language processing.',
                'specialization' => 'Machine Learning',
                'experience' => '11+ years',
                'rating' => 4.9,
                'students_taught' => 600,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Maria+Garcia&color=7F9CF5&background=EBF4FF',
                'slug' => 'maria-garcia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Martinez',
                'email' => 'david.martinez@example.com',
                'phone' => '+62 819-0123-4567',
                'bio' => 'Blockchain developer with experience in smart contracts and decentralized applications.',
                'specialization' => 'Blockchain',
                'experience' => '4+ years',
                'rating' => 4.5,
                'students_taught' => 150,
                'is_active' => false,
                'image' => 'https://ui-avatars.com/api/?name=David+Martinez&color=7F9CF5&background=EBF4FF',
                'slug' => 'david-martinez',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Jennifer Brown',
                'email' => 'jennifer.brown@example.com',
                'phone' => '+62 821-1234-5678',
                'bio' => 'Cybersecurity expert specializing in ethical hacking, penetration testing, and security audits.',
                'specialization' => 'Cybersecurity',
                'experience' => '12+ years',
                'rating' => 4.9,
                'students_taught' => 700,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Jennifer+Brown&color=7F9CF5&background=EBF4FF',
                'slug' => 'jennifer-brown',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thomas Davis',
                'email' => 'thomas.davis@example.com',
                'phone' => '+62 822-2345-6789',
                'bio' => 'Game developer with expertise in Unity, Unreal Engine, and multiplayer game architecture.',
                'specialization' => 'Game Development',
                'experience' => '6+ years',
                'rating' => 4.6,
                'students_taught' => 280,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Thomas+Davis&color=7F9CF5&background=EBF4FF',
                'slug' => 'thomas-davis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Patricia Miller',
                'email' => 'patricia.miller@example.com',
                'phone' => '+62 823-3456-7890',
                'bio' => 'IoT specialist with experience in embedded systems, sensors, and smart home technology.',
                'specialization' => 'IoT',
                'experience' => '7+ years',
                'rating' => 4.7,
                'students_taught' => 320,
                'is_active' => true,
                'image' => 'https://ui-avatars.com/api/?name=Patricia+Miller&color=7F9CF5&background=EBF4FF',
                'slug' => 'patricia-miller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Christopher Lee',
                'email' => 'christopher.lee@example.com',
                'phone' => '+62 824-4567-8901',
                'bio' => 'AR/VR developer with expertise in immersive experiences and spatial computing.',
                'specialization' => 'AR/VR Development',
                'experience' => '5+ years',
                'rating' => 4.4,
                'students_taught' => 180,
                'is_active' => false,
                'image' => 'https://ui-avatars.com/api/?name=Christopher+Lee&color=7F9CF5&background=EBF4FF',
                'slug' => 'christopher-lee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Mentor::insert($mentors);
    }
}
